/*
 * Open DAM API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	opendam "github.com/open-dam/open-dam-api/internal"
)

func main() {
	log.Printf("Server started")

	DefaultApiService := opendam.NewDefaultApiService()
	DefaultApiController := opendam.NewDefaultApiController(DefaultApiService)

	router := opendam.NewRouter(DefaultApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
