/*
 * Open DAM API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	"github.com/open-dam/open-dam-api/internal/server"
)

func main() {
	log.Printf("Server started")

	service := server.NewApiService()
	controller := server.NewController(service)

	router := server.NewRouter(controller)

	log.Fatal(http.ListenAndServe(":8080", router))
}
