/*
 * Open DAM API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package opendam

import (
	"errors"
)

// DefaultApiService is a service that implents the logic for the DefaultApiServicer
// This service should implement the business logic for every endpoint for the DefaultApi API. 
// Include any external packages or services that will be required by this service.
type DefaultApiService struct {
}

// NewDefaultApiService creates a default api service
func NewDefaultApiService() DefaultApiServicer {
	return &DefaultApiService{}
}

// DeleteAsset - 
func (s *DefaultApiService) DeleteAsset(assetId string) (interface{}, error) {
	// TODO - update DeleteAsset with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'DeleteAsset' not implemented")
}

// GetAsset - 
func (s *DefaultApiService) GetAsset(assetId string) (interface{}, error) {
	// TODO - update GetAsset with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'GetAsset' not implemented")
}

// GetAssets - 
func (s *DefaultApiService) GetAssets() (interface{}, error) {
	// TODO - update GetAssets with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'GetAssets' not implemented")
}

// GetJob - 
func (s *DefaultApiService) GetJob(jobId string) (interface{}, error) {
	// TODO - update GetJob with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'GetJob' not implemented")
}

// PostAsset - 
func (s *DefaultApiService) PostAsset() (interface{}, error) {
	// TODO - update PostAsset with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'PostAsset' not implemented")
}

// PutAsset - 
func (s *DefaultApiService) PutAsset(assetId string) (interface{}, error) {
	// TODO - update PutAsset with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'PutAsset' not implemented")
}
