name: Release Workflow
on:
  release:
    types: [published]

jobs:
  release:
    env:
      REF: ${{ github.ref }}
    name: Release Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: |
          docker build -t docker.pkg.github.com/open-dam/open-dam-api/open-dam-api:${REF##*/} -t docker.pkg.github.com/open-dam/open-dam-api/open-dam-api:latest  -f ./build/Dockerfile .

      - name: Publish Server
        run: |
          docker login docker.pkg.github.com -u Jesse0Michael -p ${{ secrets.PAT }}
          docker push docker.pkg.github.com/open-dam/open-dam-api/open-dam-api:${REF##*/}
          docker push docker.pkg.github.com/open-dam/open-dam-api/open-dam-api:latest
