name: Build
on:
  push:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    container: golang:1.14-alpine
    env:
      CGO_ENABLED: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: docker://github/super-linter:v2.1.0
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_GO: true

      - name: Test
        run: |
          go mod download
          mkdir coverage 
          go test -v ./internal/... -cover -coverprofile=coverage/info.cov
      - name: Coveralls
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage/info.cov
